In [3]:
import numpy as np

In [5]:
# 1D array
arr = np.array([12,43,5,6,8,36,49,7,5,23])
print(arr)

[12 43  5  6  8 36 49  7  5 23]


In [8]:
# Multi-dimensional array:
arrmd = np.array([[1,2,3],[4,5,6]])
arrmd

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
arrmd.dtype

dtype('int64')

In [33]:
#  BASIC 1D ARRAY SLICING

In [34]:
# Syntax: arr[start : stop : step]

print(arr[:4])

[12 43  5  6]


In [35]:
print(arr[:])

[12 43  5  6  8 36 49  7  5 23]


In [36]:
print(arr[::2])

[12  5  8 49  5]


In [37]:
print(arr[-3:])

[ 7  5 23]


In [38]:
# reverse the slice
print(arr[-3:0:-1])

[ 7 49 36  8  6  5 43]


In [39]:
print(arr[-9:4:2])

[43  6]


In [40]:
print(arr[-4:4:2])

[]


In [ ]:
#  MULTIDIMESIONAL NumPy ARRAY SLICING

In [16]:
arrmd

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
print(arrmd[0:2:1])

[[1 2 3]
 [4 5 6]]


In [18]:
# Get all rows, first two columns
print(arrmd[:, 0:2])

[[1 2]
 [4 5]]


In [19]:
# Reverse all rows
print(arrmd[::-1,:])


[[4 5 6]
 [1 2 3]]


In [20]:
# Reverse all columns
print(arrmd[:,::-1])


[[3 2 1]
 [6 5 4]]


In [21]:
# Get diagonal elements
np.diag(arrmd)

array([1, 5])

In [22]:
# Get last row
arrmd[-1, :]


array([4, 5, 6])

In [ ]:
#  reshaping in NumPy array

In [24]:
arr1 = np.array([11, 2, 30, 42, 52, 6])
reshaped = arr1.reshape(2,3)
print(reshaped)
      

[[11  2 30]
 [42 52  6]]


In [25]:
 # or arr2.flatten()
arr2 =  np.array([[11,2,30],[42,52,6]])
flattened = arr2.reshape(-1) 
print(flattened)

[11  2 30 42 52  6]


In [27]:
# Using -1 in reshape (Auto-calculate size)
reshaped = arr1.reshape(3, -1) 
print(reshaped)

[[11  2]
 [30 42]
 [52  6]]


In [28]:
arr3 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reshaped = arr3.reshape(2, 2, 2)
print(reshaped)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#  Broadcast

In [29]:
a = np.array([1, 2, 3])     
b = 1

result = a + b              
print(result)

[2 3 4]


In [30]:
c = np.array([[1, 2, 3]])     
d = np.array([[40],
              [20],
              [10]])         

result = c + d
print(result)

[[41 42 43]
 [21 22 23]
 [11 12 13]]


In [31]:
print(result + 10)

[[51 52 53]
 [31 32 33]
 [21 22 23]]
